import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import listingsRouter from "./listings";
import chatsRouter from "./chats";
import adminRouter from "./admin";
import officesRouter from "./offices";
import officeAuthRouter from "./office-auth";
import lawyersRouter from "./lawyers";
import lawyerAuthRouter from "./lawyer-auth";
import storageRouter from "./storage";
import notificationsRouter from "./notifications";
import favoritesRouter from "./favorites";
import savedSearchesRouter from "./saved-searches";
import reportsRouter from "./reports";
import networkPropertiesRouter from "./network-properties";
import dealsRouter from "./deals";
import financeRouter from "./finance";
import workshopsRouter from "./workshops";
import networkNotificationsRouter from "./network-notifications";
import inspectionsRouter from "./inspections";
import contractsRouter, { lawyerServicesRouter } from "./contracts";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/listings", listingsRouter);
router.use("/chats", chatsRouter);
router.use("/admin", adminRouter);
router.use("/offices", officesRouter);
router.use("/office/auth", officeAuthRouter);
router.use("/lawyers", lawyersRouter);
router.use("/lawyer/auth", lawyerAuthRouter);
router.use("/storage", storageRouter);
router.use("/notifications", notificationsRouter);
router.use("/favorites", favoritesRouter);
router.use("/saved-searches", savedSearchesRouter);
router.use("/reports", reportsRouter);
router.use("/network-properties", networkPropertiesRouter);
router.use("/deals", dealsRouter);
router.use("/finance", financeRouter);
router.use("/workshops", workshopsRouter);
router.use("/network-notifications", networkNotificationsRouter);
router.use("/inspections", inspectionsRouter);
router.use("/contracts", contractsRouter);
router.use("/lawyer-services", lawyerServicesRouter);

export default router;
